// Copyright (C) 2003-2025 x264 project
// SPDX-License-Identifier: GPL-2.0-only
//
// Ported from x264 common/frame.h and encoder/slicetype.c.
// x264 copyright: Copyright (C) 2003-2025 x264 project.

package imgmath

import "fmt"

// Constants for the lookahead-based scene detector.
// All values mirror the x264 lookahead analysis (encoder/slicetype.c,
// encoder/analyse.h, common/tables.c).
const (
	// MBSize is the macroblock size in pixels at lowres (8×8).
	// At full resolution this equals the H.264 16×16 macroblock.
	MBSize = 8

	// LookaheadQP is the fixed quantisation parameter used for all
	// lookahead cost estimates. Mirrors X264_LOOKAHEAD_QP = 12 + QP_BD_OFFSET
	// (QP_BD_OFFSET = 0 for 8-bit).
	LookaheadQP = 12

	// LookaheadLambda is x264_lambda_tab[LookaheadQP] = 1 for 8-bit video.
	// Source: x264/common/tables.c, row "8-15: 1,1,1,1,1,1,1,1".
	LookaheadLambda = 1

	// LowresPenalty is a small constant bias added to every per-MB inter cost
	// to discourage zero-residual lookahead blocks from causing VBV issues.
	// Mirrors `int lowres_penalty = 4` in slicetype_mb_cost (slicetype.c).
	LowresPenalty = 4

	// IntraPenalty is the constant bias added to per-MB intra costs before
	// comparing them with inter costs, favouring inter prediction slightly.
	// Mirrors `int intra_penalty = 5 * a->i_lambda` in slicetype_mb_cost.
	IntraPenalty = 5 * LookaheadLambda // = 5

	// SkipBias is added to the inter cost when the best MV is non-zero,
	// slightly favouring skip/zero-motion macroblocks over non-zero MVs.
	// Mirrors `m[l].cost += 5 * a->i_lambda` in slicetype_mb_cost.
	SkipBias = 5 * LookaheadLambda // = 5

	// MERange is the maximum integer-pixel diamond-search radius at lowres.
	// Mirrors h->param.analyse.i_me_range = 16.
	MERange = 16

	// MaxLag is the maximum supported lookahead distance (frames).
	// Bumped from 80 to support custom long-lag schedules (e.g. [15,30,45,60,90,120])
	// for testing detection of longer synthetic dissolves generated by sequence_editor
	// (see dissolve_test_xfs.json and associated cost CSV analysis).
	MaxLag = 256

	// LowresPadH and LowresPadV are the per-side padding (pixels) added to
	// each lowres plane to allow ME without bounds checks. They must be ≥
	// MERange + MBSize.
	LowresPadH = MERange + MBSize + 4 // = 28
	LowresPadV = MERange + MBSize + 4 // = 28

	// uninitMVX marks an MV x-component cache slot as not yet searched.
	// Mirrors the 0x7FFF sentinel in fenc->lowres_mvs in x264_frame_t.
	uninitMVX = int16(0x7FFF)
)

// LowresFrame holds the half-resolution luma data and associated lookahead
// cost caches for a single video frame.
//
// Ported from x264_frame_t (common/frame.h) — specifically the lowres*,
// i_cost_est*, i_intra_cost*, lowres_mvs*, and lowres_mv_costs* fields.
type LowresFrame struct {
	// planeBuf[p] is the full padded backing buffer for plane p.
	// Active pixel at column x, row y is at byte index:
	//   (y + LowresPadV) * Stride + (x + LowresPadH)
	// where x ∈ [0, Width) and y ∈ [0, Height).
	//
	// Planes[0] = integer-pel lowres luma (original half-resolution).
	// Planes[1] = H-filtered variant  (half-pixel horizontal offset).
	// Planes[2] = V-filtered variant  (half-pixel vertical offset).
	// Planes[3] = HV-filtered variant (half-pixel both offsets).
	//
	// Mirrors lowres[0..3] in x264_frame_t (common/frame.h).
	planeBuf [4][]byte

	// Stride is the number of bytes per row in each planeBuf, including
	// horizontal padding on both sides. Stride = Width + 2*LowresPadH.
	Stride int

	// Width and Height are the active luma dimensions in pixels.
	Width  int
	Height int

	// MBW and MBH are the number of 8×8 macroblocks horizontally and
	// vertically. MBW = ⌈Width/8⌉, MBH = ⌈Height/8⌉.
	MBW int
	MBH int

	// IntraCost[mb_xy] is the per-MB best-of-3 intra SATD cost, valid
	// once IntraCalc is true. Populated lazily on the first call to
	// LowresFrameCost. Mirrors fenc->i_intra_cost in slicetype_mb_cost.
	IntraCost []int32
	IntraCalc bool

	// mvCache[lag][mb_xy] caches the best integer-pel MV found when this
	// frame is the target and the reference is lag+1 frames earlier.
	// mvCache[lag] == nil means that lag has not been searched.
	// mvCache[lag][i][0] == uninitMVX means MB i not yet searched.
	// Mirrors fenc->lowres_mvs[0][lag] in x264_frame_t.
	mvCache [MaxLag][][2]int16

	// mvCostCache[lag][mb_xy] caches the best inter SATD cost for the
	// corresponding MV in mvCache.
	// Mirrors fenc->lowres_mv_costs[0][lag] in x264_frame_t.
	mvCostCache [MaxLag][]int32

	// rev holds the reverse-direction (future-reference) MV/cost caches,
	// allocated lazily on the first reverse measurement for this frame.
	// Forward and reverse measurements at the same distance are different
	// (ref = cur−k vs cur+k), so they must never share cache entries; only
	// frames inside dissolve end-refinement windows pay for the allocation.
	rev *revCaches

	// AvgLuma is the mean 8-bit luma value of the active pixel region,
	// computed once in InitLowres. Range [0, 255].
	// Used by the fade detector to distinguish dark, bright, and mid-tone frames.
	AvgLuma float32
}

// NewLowresFrame allocates a LowresFrame for the given lowres dimensions.
// The planeBuf arrays are not populated; use InitLowres to fill them.
func NewLowresFrame(width, height int) (*LowresFrame, error) {
	if width <= 0 || height <= 0 {
		return nil, fmt.Errorf("lowres_frame: invalid dimensions %dx%d", width, height)
	}
	mbw := (width + MBSize - 1) / MBSize
	mbh := (height + MBSize - 1) / MBSize
	return &LowresFrame{
		Width:     width,
		Height:    height,
		MBW:       mbw,
		MBH:       mbh,
		IntraCost: make([]int32, mbw*mbh),
	}, nil
}

// planeOffset returns the byte index into planeBuf[p] for pixel (x, y),
// where x and y may range into the padding region:
//
//	x ∈ [−LowresPadH, Width+LowresPadH)
//	y ∈ [−LowresPadV, Height+LowresPadV)
func (f *LowresFrame) planeOffset(x, y int) int {
	return (y+LowresPadV)*f.Stride + (x + LowresPadH)
}

// revCaches holds the reverse-direction MV/cost caches (see LowresFrame.rev).
type revCaches struct {
	mv   [MaxLag][][2]int16
	cost [MaxLag][]int32
}

// ensureMVCache allocates and initialises the MV and cost cache slices for a
// given lag index if they have not been allocated yet.
func (f *LowresFrame) ensureMVCache(lag int) {
	if f.mvCache[lag] != nil {
		return
	}
	n := f.MBW * f.MBH
	f.mvCache[lag] = make([][2]int16, n)
	f.mvCostCache[lag] = make([]int32, n)
	for i := range f.mvCache[lag] {
		f.mvCache[lag][i][0] = uninitMVX
	}
}

// mvCacheDir returns the MV and cost cache slices for the given lag and
// direction, allocating them if needed. rev=true selects the reverse
// (future-reference) caches, which are kept fully separate from the forward
// ones: the caches are keyed by slot only, so sharing entries across
// directions would silently return the other direction's cost.
func (f *LowresFrame) mvCacheDir(lag int, rev bool) (mv [][2]int16, cost []int32) {
	if !rev {
		f.ensureMVCache(lag)
		return f.mvCache[lag], f.mvCostCache[lag]
	}
	if f.rev == nil {
		f.rev = &revCaches{}
	}
	if f.rev.mv[lag] == nil {
		n := f.MBW * f.MBH
		f.rev.mv[lag] = make([][2]int16, n)
		f.rev.cost[lag] = make([]int32, n)
		for i := range f.rev.mv[lag] {
			f.rev.mv[lag][i][0] = uninitMVX
		}
	}
	return f.rev.mv[lag], f.rev.cost[lag]
}

// MVCached reports whether the MV cache for a given lag has been fully
// populated (i.e. at least one MB has been searched).
func (f *LowresFrame) MVCached(lag int) bool {
	return lag >= 0 && lag < MaxLag &&
		f.mvCache[lag] != nil &&
		f.mvCache[lag][0][0] != uninitMVX
}
