package pipeline

import (
	"encoding/json"
	"fmt"
	"testing"

	"pgregory.net/rapid"
)

// TestPropertyConfigRoundTrip verifies that marshal → unmarshal → marshal
// produces identical JSON output for randomly generated valid Configs.
func TestPropertyConfigRoundTrip(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		cfg := genConfig(t)

		b1, err := json.Marshal(cfg)
		if err != nil {
			t.Fatalf("first marshal: %v", err)
		}

		var cfg2 Config
		if err := json.Unmarshal(b1, &cfg2); err != nil {
			t.Fatalf("unmarshal: %v", err)
		}

		b2, err := json.Marshal(cfg2)
		if err != nil {
			t.Fatalf("second marshal: %v", err)
		}

		if string(b1) != string(b2) {
			t.Fatalf("round-trip mismatch:\n  first:  %s\n  second: %s", b1, b2)
		}
	})
}

// TestPropertyConfigParseValid verifies that configs generated by genConfig
// always pass ParseConfig validation.
func TestPropertyConfigParseValid(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		cfg := genConfig(t)
		b, err := json.Marshal(cfg)
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		if _, err := ParseConfig(b); err != nil {
			t.Fatalf("ParseConfig rejected valid config: %v\njson: %s", err, b)
		}
	})
}

// TestPropertyStateTransitionsNoPanic verifies that random sequences of
// SetState calls never panic, always returning nil or ErrInvalidStateTransition.
func TestPropertyStateTransitionsNoPanic(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		cfg := &Config{
			SchemaVersion: "1.0",
			Inputs:        []Input{{ID: "in1", URL: "test.mp4", Streams: []StreamSelect{{Type: "video"}}}},
			Outputs:       []Output{{ID: "out1", URL: "out.mp4"}},
		}
		p, err := NewPipeline(cfg)
		if err != nil {
			t.Skip("av.CheckVersion failed:", err)
		}

		states := []State{StateNull, StateReady, StatePaused, StatePlaying}
		numOps := rapid.IntRange(1, 50).Draw(t, "numOps")

		for i := 0; i < numOps; i++ {
			target := rapid.SampledFrom(states).Draw(t, "target")
			err := p.SetState(target)
			if err != nil {
				if _, ok := err.(*ErrInvalidStateTransition); !ok {
					// Non-transition errors are okay (e.g. resource setup failures).
					// The key property is: no panic.
					_ = err
				}
			}
		}
	})
}

// genConfig generates a random but valid Config.
func genConfig(t *rapid.T) *Config {
	numInputs := rapid.IntRange(1, 4).Draw(t, "numInputs")
	numOutputs := rapid.IntRange(1, 4).Draw(t, "numOutputs")
	numNodes := rapid.IntRange(0, 6).Draw(t, "numNodes")

	cfg := Config{
		SchemaVersion: "1.0",
	}

	streamTypes := []string{"video", "audio", "subtitle", "data"}

	for i := 0; i < numInputs; i++ {
		id := rapid.StringMatching(`^[a-z]{2,6}$`).Draw(t, "inputID")
		url := rapid.StringMatching(`^[a-z0-9_]{1,10}\.(mp4|mkv|avi|ts)$`).Draw(t, "inputURL")
		numStreams := rapid.IntRange(0, 3).Draw(t, "numStreams")
		var streams []StreamSelect
		for j := 0; j < numStreams; j++ {
			streams = append(streams, StreamSelect{
				InputIndex: rapid.IntRange(0, 3).Draw(t, "streamIdx"),
				Type:       rapid.SampledFrom(streamTypes).Draw(t, "streamType"),
				Track:      rapid.IntRange(0, 2).Draw(t, "streamTrack"),
			})
		}
		cfg.Inputs = append(cfg.Inputs, Input{
			ID:      fmt.Sprintf("in_%d_%s", i, id),
			URL:     url,
			Streams: streams,
		})
	}

	for i := 0; i < numOutputs; i++ {
		id := rapid.StringMatching(`^[a-z]{2,6}$`).Draw(t, "outputID")
		url := rapid.StringMatching(`^[a-z0-9_]{1,10}\.(mp4|mkv|avi|ts)$`).Draw(t, "outputURL")
		out := Output{
			ID:  fmt.Sprintf("out_%d_%s", i, id),
			URL: url,
		}
		if rapid.Bool().Draw(t, "hasCodecVideo") {
			out.CodecVideo = rapid.SampledFrom([]string{"libx264", "libx265", "copy"}).Draw(t, "codecVideo")
		}
		if rapid.Bool().Draw(t, "hasCodecAudio") {
			out.CodecAudio = rapid.SampledFrom([]string{"aac", "libmp3lame", "copy"}).Draw(t, "codecAudio")
		}
		if rapid.Bool().Draw(t, "hasCodecSubtitle") {
			out.CodecSubtitle = rapid.SampledFrom([]string{"mov_text", "srt", "copy"}).Draw(t, "codecSub")
		}
		if rapid.Bool().Draw(t, "hasBSFVideo") {
			out.BSFVideo = rapid.SampledFrom([]string{"h264_mp4toannexb", "hevc_mp4toannexb"}).Draw(t, "bsfVideo")
		}
		if rapid.Bool().Draw(t, "hasBSFAudio") {
			out.BSFAudio = rapid.SampledFrom([]string{"aac_adtstoasc"}).Draw(t, "bsfAudio")
		}
		cfg.Outputs = append(cfg.Outputs, out)
	}

	nodeTypes := []string{"filter", "encoder"}
	edgeTypes := []string{"video", "audio", "subtitle", "data"}

	for i := 0; i < numNodes; i++ {
		id := rapid.StringMatching(`^[a-z]{2,6}$`).Draw(t, "nodeID")
		cfg.Graph.Nodes = append(cfg.Graph.Nodes, NodeDef{
			ID:     fmt.Sprintf("n_%d_%s", i, id),
			Type:   rapid.SampledFrom(nodeTypes).Draw(t, "nodeType"),
			Filter: rapid.StringMatching(`^[a-z_]{2,10}$`).Draw(t, "filter"),
		})
	}

	// Generate valid edges between existing IDs.
	allIDs := make([]string, 0, numInputs+numOutputs+numNodes)
	for _, inp := range cfg.Inputs {
		allIDs = append(allIDs, inp.ID)
	}
	for _, n := range cfg.Graph.Nodes {
		allIDs = append(allIDs, n.ID)
	}
	for _, out := range cfg.Outputs {
		allIDs = append(allIDs, out.ID)
	}
	numEdges := rapid.IntRange(0, 8).Draw(t, "numEdges")
	for i := 0; i < numEdges; i++ {
		from := rapid.SampledFrom(allIDs).Draw(t, "edgeFrom")
		to := rapid.SampledFrom(allIDs).Draw(t, "edgeTo")
		cfg.Graph.Edges = append(cfg.Graph.Edges, EdgeDef{
			From: from,
			To:   to,
			Type: rapid.SampledFrom(edgeTypes).Draw(t, "edgeType"),
		})
	}

	if rapid.Bool().Draw(t, "hasGlobalOpts") {
		cfg.GlobalOptions = Options{
			Threads:   rapid.IntRange(0, 16).Draw(t, "threads"),
			Realtime:  rapid.Bool().Draw(t, "realtime"),
		}
		if rapid.Bool().Draw(t, "hasHWAccel") {
			cfg.GlobalOptions.HardwareAccel = rapid.SampledFrom([]string{"cuda", "vaapi", "videotoolbox"}).Draw(t, "hwAccel")
		}
		if rapid.Bool().Draw(t, "hasHWDevice") {
			cfg.GlobalOptions.HardwareDevice = rapid.SampledFrom([]string{"/dev/dri/renderD128", "0"}).Draw(t, "hwDevice")
		}
	}

	return &cfg
}
