#!/usr/bin/env python3
"""Generate internal/gui/help_overrides_gen.go from private_local/nodes.csv.

Usage:
    python3 scripts/gen_help_overrides.py

Reads the 'help override' column for every encoder row and emits a Go source
file that the GUI handler uses to replace AVOption help strings with improved
descriptions before caching and serving them.
"""

import csv
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(REPO_ROOT, "private_local", "nodes.csv")
OUT_PATH = os.path.join(REPO_ROOT, "internal", "gui", "help_overrides_gen.go")


def go_str(s: str) -> str:
    """Emit s as a Go double-quoted string literal."""
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    s = s.replace("\n", "\\n")
    s = s.replace("\t", "\\t")
    return f'"{s}"'


def main():
    if not os.path.exists(CSV_PATH):
        sys.exit(f"error: {CSV_PATH} not found")

    # Collect (node_name, parameter) -> help_override, keeping the first
    # non-empty value when duplicate keys appear (e.g. two 'profile' rows).
    overrides: dict[tuple[str, str], str] = {}
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["node_type"] != "encoder":
                continue
            ho = row["help override"].strip()
            if not ho:
                continue
            key = (row["node_name"], row["parameter"])
            if key not in overrides:
                overrides[key] = ho

    # Group by encoder name.
    by_encoder: dict[str, dict[str, str]] = {}
    for (enc, param), text in sorted(overrides.items()):
        by_encoder.setdefault(enc, {})[param] = text

    lines = [
        "// Code generated by scripts/gen_help_overrides.py; DO NOT EDIT.",
        "",
        "// Copyright (C) 2026 Thomas Vaughan",
        "// SPDX-License-Identifier: LGPL-2.1-or-later",
        "",
        "package gui",
        "",
        'import "github.com/MediaMolder/MediaMolder/av"',
        "",
        "// encoderHelpOverrides maps encoder name → option name → improved help text.",
        "// Generated from private_local/nodes.csv; update by running",
        "// scripts/gen_help_overrides.py.",
        "var encoderHelpOverrides = map[string]map[string]string{",
    ]

    for enc_name in sorted(by_encoder):
        params = by_encoder[enc_name]
        lines.append(f"\t{go_str(enc_name)}: {{")
        for param in sorted(params):
            lines.append(f"\t\t{go_str(param)}: {go_str(params[param])},")
        lines.append("\t},")

    lines += [
        "}",
        "",
        "// applyEncoderHelpOverrides replaces the Help field of any EncoderOption",
        "// whose (encoder, name) pair has an entry in encoderHelpOverrides.",
        "func applyEncoderHelpOverrides(info *av.EncoderInfo) {",
        "\tpm, ok := encoderHelpOverrides[info.Name]",
        "\tif !ok {",
        "\t\treturn",
        "\t}",
        "\tfor i := range info.Options {",
        "\t\tif h, found := pm[info.Options[i].Name]; found {",
        "\t\t\tinfo.Options[i].Help = h",
        "\t\t}",
        "\t}",
        "}",
        "",
    ]

    out = "\n".join(lines)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(out)

    print(f"wrote {OUT_PATH} ({len(overrides)} overrides across {len(by_encoder)} encoders)")


if __name__ == "__main__":
    main()
