#!/usr/bin/env python3
"""Generate internal/gui/help_overrides_gen.go from private_local/nodes.csv.

Usage:
    python3 scripts/gen_help_overrides.py

Reads the 'help override' and 'extended help' columns for every encoder row
and emits a Go source file that the GUI handler uses to:
  - Replace AVOption help strings with improved descriptions (help override).
  - Set a longer prose ExtendedHelp field surfaced via a "?" button in the UI.
"""

import csv
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(REPO_ROOT, "private_local", "nodes.csv")
OUT_PATH = os.path.join(REPO_ROOT, "internal", "gui", "help_overrides_gen.go")


def go_str(s: str) -> str:
    """Emit s as a Go double-quoted string literal."""
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    s = s.replace("\n", "\\n")
    s = s.replace("\t", "\\t")
    return f'"{s}"'


def main():
    if not os.path.exists(CSV_PATH):
        sys.exit(f"error: {CSV_PATH} not found")

    # Collect per-key data, keeping the first non-empty value on duplicates.
    overrides: dict[tuple[str, str], str] = {}
    extended: dict[tuple[str, str], str] = {}
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["node_type"] != "encoder":
                continue
            key = (row["node_name"], row["parameter"])
            ho = row["help override"].strip()
            if ho and key not in overrides:
                overrides[key] = ho
            eh = row["extended help"].strip()
            if eh and key not in extended:
                extended[key] = eh

    def group_by_encoder(d: dict[tuple[str, str], str]) -> dict[str, dict[str, str]]:
        out: dict[str, dict[str, str]] = {}
        for (enc, param), text in sorted(d.items()):
            out.setdefault(enc, {})[param] = text
        return out

    by_encoder_overrides = group_by_encoder(overrides)
    by_encoder_extended = group_by_encoder(extended)

    def emit_map(var_name: str, by_encoder: dict[str, dict[str, str]]) -> list[str]:
        lines = [f"var {var_name} = map[string]map[string]string{{"]
        for enc_name in sorted(by_encoder):
            params = by_encoder[enc_name]
            lines.append(f"\t{go_str(enc_name)}: {{")
            for param in sorted(params):
                lines.append(f"\t\t{go_str(param)}: {go_str(params[param])},")
            lines.append("\t},")
        lines.append("}")
        return lines

    lines = [
        "// Code generated by scripts/gen_help_overrides.py; DO NOT EDIT.",
        "",
        "// Copyright (C) 2026 Thomas Vaughan",
        "// SPDX-License-Identifier: LGPL-2.1-or-later",
        "",
        "package gui",
        "",
        'import "github.com/MediaMolder/MediaMolder/av"',
        "",
        "// encoderHelpOverrides maps encoder name → option name → improved help text.",
        "// Generated from private_local/nodes.csv; update by running",
        "// scripts/gen_help_overrides.py.",
    ]
    lines += emit_map("encoderHelpOverrides", by_encoder_overrides)
    lines += [
        "",
        "// encoderExtendedHelp maps encoder name → option name → extended prose help.",
        "// Surfaced in the GUI behind a small '?' button per option.",
        "// Generated from private_local/nodes.csv.",
    ]
    lines += emit_map("encoderExtendedHelp", by_encoder_extended)
    lines += [
        "",
        "// applyEncoderHelpOverrides replaces the Help field of any EncoderOption",
        "// whose (encoder, name) pair has an entry in encoderHelpOverrides.",
        "func applyEncoderHelpOverrides(info *av.EncoderInfo) {",
        "\tpm, ok := encoderHelpOverrides[info.Name]",
        "\tif !ok {",
        "\t\treturn",
        "\t}",
        "\tfor i := range info.Options {",
        "\t\tif h, found := pm[info.Options[i].Name]; found {",
        "\t\t\tinfo.Options[i].Help = h",
        "\t\t}",
        "\t}",
        "}",
        "",
        "// applyEncoderExtendedHelp sets the ExtendedHelp field on any EncoderOption",
        "// whose (encoder, name) pair has prose text in encoderExtendedHelp.",
        "func applyEncoderExtendedHelp(info *av.EncoderInfo) {",
        "\tpm, ok := encoderExtendedHelp[info.Name]",
        "\tif !ok {",
        "\t\treturn",
        "\t}",
        "\tfor i := range info.Options {",
        "\t\tif h, found := pm[info.Options[i].Name]; found {",
        "\t\t\tinfo.Options[i].ExtendedHelp = h",
        "\t\t}",
        "\t}",
        "}",
        "",
    ]

    out = "\n".join(lines)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(out)

    print(
        f"wrote {OUT_PATH} "
        f"({len(overrides)} help overrides, {len(extended)} extended help entries "
        f"across {len(set(k[0] for k in {**overrides, **extended}))} encoders)"
    )


if __name__ == "__main__":
    main()
